services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local1234!
      POSTGRES_DB: localDB
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
